
import csv

enrichments = {
    "Air conditioner": (["Heater", "Furnace", "Sweat"], "Household"),
    "Air filter": (["Polluter", "Clogger", "Dirt"], "Household"),
    "Slow Poke": (["Speedster", "Rusher", "Flash"], "Personality"),
    "Airfare": (["Walk-free", "Stay-paid", "Ground-cost"], "Travel"),
    "Airplane": (["Submarine", "Train", "Car"], "Travel"),
    "Airplane wing": (["Submarine-fin", "Train-wheel", "Car-door"], "Travel"),
    "Airport": (["Station", "Port", "Stop"], "Travel"),
    "Airport lounge": (["Station-bench", "Street-corner", "Bus-stop"], "Travel"),
    "Window seat": (["Aisle-stand", "Middle-floor", "Roof-lay"], "Travel"),
    "Kidney": (["Lung", "Heart", "Skin"], "Body"),
    "Babysitting": (["Adult-ignoring", "Elder-leaving", "Self-care"], "Jobs"),
    "Backpack": (["Briefcase", "Purse", "Pocket"], "Items"),
    "Bacon": (["Lettuce", "Tomato", "Tofu"], "Food"),
    "Softball": (["Hard-rock", "Baseball", "Brick"], "Sports"),
    "Baggage claim": (["Luggage-drop", "Bag-lose", "Case-toss"], "Travel"),
    "Banana split": (["Apple-whole", "Grape-join", "Melon-fix"], "Food"),
    "Basketball": (["Football", "Golfball", "Puck"], "Sports"),
    "Basketball hoop": (["Soccer-goal", "Golf-hole", "Hockey-net"], "Sports"),
    "Bassoon": (["Flute", "Piccolo", "Whistle"], "Music"),
    "Beachball": (["Snow-brick", "Dirt-clod", "Rock"], "Fun"),
    "Bedroom": (["Kitchen", "Office", "Garage"], "House"),
    "Bicycle": (["Car", "Truck", "Bus"], "Transport"),
    "Bicycle rack": (["Car-garage", "Truck-stop", "Bus-depot"], "Transport"),
    "Birthday cake": (["Funeral-pie", "Wedding-soup", "Divorce-bread"], "Food"),
    "Birthday candle": (["Funeral-dark", "Wedding-light", "Party-bulb"], "Items"),
    "Black tea": (["White-coffee", "Green-juice", "Red-soda"], "Drink"),
    "Blueberry": (["Red-cherry", "Yellow-lemon", "Orange"], "Food"),
    "Bookmark": (["Page-ripper", "Book-burner", "Text-eraser"], "Items"),
    "Bookworm": (["Movie-star", "TV-addict", "Game-player"], "Personality"),
    "Breakfast": (["Dinner", "Supper", "Lunch"], "Food"),
    "Bubble gum": (["Hard-candy", "Chocolate", "Mints"], "Candy"),
    "Bullet train": (["Snail-cart", "Turtle-walk", "Slug-crawl"], "Transport"),
    "Cabin crew": (["Cockpit-solo", "Ground-staff", "Passenger"], "Travel"),
    "Cabin lights": (["Cargo-darks", "Street-lamps", "Sun-shine"], "Travel"),
    "Caboose": (["Engine", "Locomotive", "Front"], "Transport"),
    "Calculator": (["Guesser", "Estimator", "Dreamer"], "Tools"),
    "Candlestick": (["Light-bulb", "Flashlight", "Sun"], "Items"),
    "Candy apple": (["Sour-grape", "Salty-nut", "Bitter-lemon"], "Food"),
    "Candy bar": (["Veggie-stick", "Fruit-slice", "Meat-slab"], "Food"),
    "Candy cane": (["Sour-stick", "Salty-pretzel", "Bitter-root"], "Food"),
    "Capture the flag": (["Drop-ball", "Lose-game", "Give-up"], "Games"),
    "Car horn": (["Bike-bell", "Train-whistle", "Ship-blast"], "Car"),
    "Car keys": (["House-lock", "Bike-chain", "Safe-combo"], "Car"),
    "Car seat": (["Bench", "Stool", "Chair"], "Car"),
    "Car wash": (["Dirt-road", "Mud-pit", "Dust-storm"], "Car"),
    "Carpool": (["Solo-drive", "Walk-alone", "Bike-single"], "Car"),
    "Carrot cake": (["Meat-loaf", "Fish-pie", "Steak"], "Food"),
    "Carry-on": (["Check-in", "Leave-behind", "Drop-off"], "Travel"),
    "Drop Off": (["Pick-up", "Carry-on", "Take-away"], "Travel"),
    "Caterpillar": (["Butterfly", "Moth", "Worm"], "Animals"),
    "Ceiling Fan": (["Floor-heater", "Wall-light", "Table-lamp"], "House"),
    "Cereal bowl": (["Soup-plate", "Salad-dish", "Dinner-tray"], "Food"),
    "Chai latte": (["Black-coffee", "Green-tea", "Water"], "Drink"),
    "Chalk dust": (["Ink-blot", "Paint-spill", "Marker-stain"], "School"),
    "Chalk eraser": (["Pen-cap", "Pencil-tip", "Marker-lid"], "School"),
    "Chalkboard": (["Whiteboard", "Smartboard", "Paper"], "School"),
    "Checked bag": (["Carry-on", "Purse", "Backpack"], "Travel"),
    "Cheerleader": (["Booer", "Heckler", "Critic"], "Sports"),
    "Cheese stick": (["Meat-ball", "Bread-loaf", "Fruit-cup"], "Food"),
    "Cheeseburger": (["Hamburger", "Hotdog", "Taco"], "Food"),
    "Cheesecake": (["Pie", "Tart", "Brownie"], "Food"),
    "Cherry tart": (["Apple-pie", "Lemon-bar", "Choco-cake"], "Food"),
    "Chicken nuggets": (["Beef-steak", "Pork-chop", "Fish-filet"], "Food"),
    "Chocolate": (["Vanilla", "Strawberry", "Mint"], "Food"),
    "Chocolate bar": (["Vanilla-cone", "Fruit-roll", "Nut-bar"], "Food"),
    "Circus tent": (["Office-block", "House-brick", "Shop-glass"], "Fun"),
    "Clarinet": (["Trumpet", "Drum", "Guitar"], "Music"),
    "Cloudburst": (["Sun-drought", "Wind-dry", "Sand-storm"], "Weather"),
    "Clown": (["Mime", "Actor", "Lawyer"], "Fun"),
    "Clutch": (["Release", "Drop", "Let-go"], "Car"),
    "Coconut": (["Peanut", "Walnut", "Almond"], "Food"),
    "Coffee": (["Tea", "Water", "Juice"], "Drink"),
    "Coffee pot": (["Tea-kettle", "Juice-jug", "Water-pitcher"], "Drink"),
    "Colored pencils": (["Black-pens", "White-chalk", "Grey-lead"], "Art"),
    "Compass": (["Map", "GPS", "Star"], "Tools"),
    "Compass tool": (["Ruler", "Protractor", "Scale"], "Tools"),
    "Conductor": (["Passenger", "Driver", "Pilot"], "Transport"),
    "Control tower": (["Ground-crew", "Runway", "Gate"], "Travel"),
    "Cookie jar": (["Fruit-bowl", "Veggie-bin", "Bread-box"], "Food"),
    "Hand in the Cookie Jar": (["Foot-in-mouth", "Head-in-sand", "Eye-on-ball"], "Idioms"),
    "Copilot": (["Pilot", "Passenger", "Steward"], "Travel"),
    "Corn dog": (["Hot-dog", "Burger", "Pizza"], "Food"),
    "Cornbread": (["Wheat-toast", "Rye-bun", "White-slice"], "Food"),
    "Cotton candy": (["Rock-candy", "Hard-tack", "Jaw-breaker"], "Candy"),
    "Cotton gloves": (["Wool-socks", "Leather-boots", "Rubber-shoes"], "Clothing"),
    "Crayons": (["Markers", "Paints", "Pencils"], "Art"),
    "Crosswalk": (["Jay-walk", "Run-across", "Stay-put"], "City"),
    "Cup noodles": (["Plate-pasta", "Bowl-rice", "Dish-stew"], "Food"),
    "Cupcake": (["Muffin", "Donut", "Scone"], "Food"),
    "Cupcake sprinkles": (["Choco-chips", "Nuts", "Raisins"], "Food"),
    "Cupholder": (["Plate-rack", "Dish-drain", "Bowl-stack"], "Car"),
    "Departure time": (["Arrival-date", "Stay-length", "Return-trip"], "Travel"),
    "Graduation Diploma": (["Birth-cert", "Death-warrant", "Marriage-license"], "Life"),
    "Dirty Mind": (["Clean-slate", "Pure-heart", "Blank-page"], "Personality"),
    "Dishwasher": (["Sink", "Sponge", "Towel"], "House"),
    "Dodgeball": (["Catch", "Tag", "Hide"], "Sports"),
    "Donuts": (["Bagels", "Croissants", "Rolls"], "Food"),
    "Door knob": (["Window-latch", "Gate-hook", "Wall-switch"], "House"),
    "Doorbell": (["Knocker", "Peephole", "Mat"], "House"),
    "Dumbbell": (["Barbell", "Weight", "Machine"], "Gym"),
    "Dr Pepper": (["Mr-Pibb", "Coke", "Pepsi"], "Drink"),
    "Dragonfly": (["Butterfly", "Bee", "Fly"], "Animals"),
    "Driveway": (["Parkway", "Highway", "Street"], "House"),
    "Dryer": (["Washer", "Line", "Rack"], "House"),
    "Economy seat": (["First-class", "Business", "Pilot"], "Travel"),
    "Eggroll": (["Spring-roll", "Dumpling", "Bun"], "Food"),
    "Emergency exit": (["Main-entrance", "Front-door", "Side-gate"], "Safety"),
    "Energy bar": (["Sleep-pill", "Calm-tea", "Relax-mat"], "Food"),
    "Energy drink": (["Water", "Milk", "Juice"], "Drink"),
    "Eraser": (["Pen", "Marker", "Chalk"], "School"),
    "Field trip": (["Home-stay", "Class-work", "Desk-job"], "School"),
    "Final boarding": (["First-call", "Pre-board", "Check-in"], "Travel"),
    "Fire eater": (["Water-drinker", "Ice-chewer", "Air-breather"], "Fun"),
    "Fire hose": (["Garden-hose", "Straw", "Pipe"], "Safety"),
    "Firefighter": (["Arsonist", "Police", "Doctor"], "Jobs"),
    "Firetruck": (["Police-car", "Ambulance", "Taxi"], "City"),
    "Fireworks": (["Sparklers", "Flares", "Lights"], "Fun"),
    "First class": (["Economy", "Coach", "Cargo"], "Travel"),
    "Flashlight": (["Candle", "Lamp", "Sun"], "Tools"),
    "Flight/Fly": (["Drive", "Walk", "Swim"], "Travel"),
    "Flight attendant": (["Pilot", "Passenger", "Guard"], "Travel"),
    "Flight number": (["Seat-number", "Gate-code", "Bag-tag"], "Travel"),
    "Football": (["Soccer", "Rugby", "Tennis"], "Sports"),
    "Fortune Cookie": (["Fact-file", "News-paper", "Text-book"], "Food"),
    "Four square": (["Hop-scotch", "Tag", "Hide"], "Games"),
    "Freeze tag": (["Melt-down", "Burn-up", "Thaw-out"], "Games"),
    "French fries": (["Baked-potato", "Mashed", "Boiled"], "Food"),
    "French horn": (["English-flute", "German-drum", "Spanish-guitar"], "Music"),
    "Fried rice": (["Steamed", "Boiled", "Raw"], "Food"),
    "Fudge": (["Toffee", "Caramel", "Nougat"], "Candy"),
    "Fuel gauge": (["Speedometer", "Thermometer", "Clock"], "Car"),
    "Funnel cake": (["Pancake", "Waffle", "Crepe"], "Food"),
    "Garage door": (["Front-gate", "Back-door", "Side-entry"], "House"),
    "Garden hose": (["Fire-hose", "Straw", "Pipe"], "Garden"),
    "Gas pedal": (["Brake", "Clutch", "Wheel"], "Car"),
    "Gas pump": (["Charger", "Plug", "Socket"], "Car"),
    "Gas station": (["Rest-stop", "Diner", "Motel"], "Travel"),
    "Gear shift": (["Steering", "Brake", "Pedal"], "Car"),
    "Gingerbread": (["Shortbread", "Sugar-cookie", "Oatmeal"], "Food"),
    "Glovebox": (["Trunk", "Hood", "Roof"], "Car"),
    "Glue stick": (["Tape", "Staple", "Clip"], "School"),
    "Goldfish": (["Shark", "Whale", "Tuna"], "Animals"),
    "Graduation cap": (["Party-hat", "Helmet", "Crown"], "School"),
    "Green beans": (["Carrots", "Peas", "Corn"], "Food"),
    "Green tea": (["Black-coffee", "Red-wine", "White-milk"], "Drink"),
    "Grizzly bear": (["Teddy", "Panda", "Polar"], "Animals"),
    "Gym shoes": (["Dress-shoes", "Boots", "Sandals"], "Clothing"),
    "Hall pass": (["Detention", "Suspension", "Expulsion"], "School"),
    "Hamburger": (["Hotdog", "Pizza", "Taco"], "Food"),
    "Haunted house": (["Fun-house", "Doll-house", "Tree-house"], "Fun"),
    "Headlight": (["Taillight", "Brake-light", "Turn-signal"], "Car"),
    "Headphones": (["Speakers", "Radio", "Stereo"], "Tech"),
    "Herbal tea": (["Soda", "Beer", "Wine"], "Drink"),
    "Hide and seek": (["Tag", "Chase", "Race"], "Games"),
    "Highlighter": (["Pen", "Pencil", "Marker"], "School"),
    "Highway": (["Street", "Road", "Lane"], "Travel"),
    "Highway exit": (["Entrance", "Ramp", "Lane"], "Travel"),
    "History book": (["Sci-fi", "Fantasy", "Comic"], "School"),
    "Homework": (["Classwork", "Test", "Quiz"], "School"),
    "Honeycomb": (["Beehive", "Nest", "Web"], "Nature"),
    "Hopscotch": (["Jump-rope", "Tag", "Hide"], "Games"),
    "Hot chocolate": (["Iced-tea", "Lemonade", "Water"], "Drink"),
    "Hot cocoa": (["Cold-milk", "Juice", "Soda"], "Drink"),
    "Hot fudge": (["Whipped-cream", "Sprinkles", "Cherry"], "Food"),
    "Hot sauce": (["Ketchup", "Mustard", "Mayo"], "Food"),
    "Hot tea": (["Iced-coffee", "Slushie", "Shake"], "Drink"),
    "Hotdog": (["Burger", "Pizza", "Taco"], "Food"),
    "Hotel": (["Motel", "Inn", "Hostel"], "Travel"),
    "Hubcap": (["Tire", "Rim", "Wheel"], "Car"),
    "Ice cream": (["Yogurt", "Sorbet", "Gelato"], "Food"),
    "Ice cream cone": (["Cup", "Bowl", "Dish"], "Food"),
    "Ice cream sundae": (["Banana-split", "Cone", "Shake"], "Food"),
    "Ice cube": (["Water", "Steam", "Vapor"], "Science"),
    "Ice skate": (["Roller", "Blade", "Wheel"], "Sports"),
    "Ice water": (["Hot-tea", "Warm-milk", "Boiling"], "Drink"),
    "Iceberg": (["Glacier", "Snow", "Frost"], "Nature"),
    "Iced tea": (["Hot-coffee", "Warm-cider", "Soup"], "Drink"),
    "Insure": (["Risk", "Gamble", "Bet"], "Money"),
    "Jam jar": (["Pickle-jar", "Can", "Box"], "Food"),
    "Jellyfish": (["Starfish", "Crab", "Lobster"], "Animals"),
    "Juggler": (["Clown", "Acrobat", "Mime"], "Fun"),
    "Jump rope": (["Hula-hoop", "Ball", "Bat"], "Games"),
    "Jumper cables": (["Tow-rope", "Chain", "Strap"], "Car"),
    "Ketchup": (["Mustard", "Mayo", "Relish"], "Food"),
    "Keyboard": (["Mouse", "Screen", "Monitor"], "Tech"),
    "Kite string": (["Fishing-line", "Thread", "Yarn"], "Fun"),
    "Kiwi fruit": (["Apple", "Orange", "Banana"], "Food"),
    "Ladybug": (["Beetle", "Ant", "Fly"], "Animals"),
    "Landing gear": (["Wings", "Tail", "Nose"], "Travel"),
    "Laptop": (["Desktop", "Tablet", "Phone"], "Tech"),
    "Lawn mower": (["Rake", "Shovel", "Hoe"], "Garden"),
    "Layover": (["Direct", "Non-stop", "Through"], "Travel"),
    "Lemon drop": (["Gum-drop", "Mint", "Chew"], "Candy"),
    "Lemonade": (["Limeade", "Punch", "Soda"], "Drink"),
    "Lemonade stand": (["Store", "Shop", "Mart"], "Fun"),
    "License": (["Permit", "Card", "ID"], "Legal"),
    "License plate": (["Bumper", "Sticker", "Decal"], "Car"),
    "Life vest": (["Float", "Ring", "Buoy"], "Safety"),
    "Lighthouse": (["Beacon", "Lamp", "Torch"], "Sea"),
    "Locker": (["Closet", "Shelf", "Box"], "School"),
    "Locomotive": (["Car", "Caboose", "Train"], "Transport"),
    "Lollipop": (["Sucker", "Pop", "Candy"], "Candy"),
    "Lost luggage": (["Found", "Claimed", "Safe"], "Travel"),
    "Luggage cart": (["Trolley", "Wagon", "Barrow"], "Travel"),
    "Luggage rack": (["Shelf", "Bin", "Hook"], "Travel"),
    "Lunchbox": (["Bag", "Tray", "Plate"], "School"),
    "Magic show": (["Play", "Movie", "Concert"], "Fun"),
    "Magician": (["Wizard", "Witch", "Sorcerer"], "Fun"),
    "Mailbox": (["Inbox", "Outbox", "Slot"], "House"),
    "Mapquest": (["Google", "Apple", "Waze"], "Tech"),
    "Marshmallow": (["Chocolate", "Graham", "Cracker"], "Food"),
    "Mashed potatoes": (["Fries", "Chips", "Baked"], "Food"),
    "Math problem": (["Word-search", "Crossword", "Puzzle"], "School"),
    "Mayonnaise": (["Mustard", "Ketchup", "Relish"], "Food"),
    "Meatballs": (["Sausage", "Patty", "Link"], "Food"),
    "Merry-go-round": (["Slide", "Swing", "Seesaw"], "Fun"),
    "Metro card": (["Token", "Ticket", "Pass"], "Travel"),
    "Microwave": (["Oven", "Stove", "Grill"], "Kitchen"),
    "Milk carton": (["Jug", "Bottle", "Bag"], "Drink"),
    "Milkshake": (["Malt", "Float", "Smoothie"], "Drink"),
    "Mindset": (["Mood", "Attitude", "Vibe"], "Psych"),
    "Mindful": (["Aware", "Alert", "Awake"], "Psych"),
    "Minecraft": (["Roblox", "Fortnite", "Mario"], "Games"),
    "Mineral water": (["Tap", "Spring", "Well"], "Drink"),
    "Mocha": (["Latte", "Cappuccino", "Espresso"], "Drink"),
    "Monkey bars": (["Slide", "Swing", "Ladder"], "Fun"),
    "Moonlight": (["Sunlight", "Starlight", "Lamplight"], "Nature"),
    "Motel": (["Hotel", "Inn", "Lodge"], "Travel"),
    "Muffins": (["Scones", "Biscuits", "Rolls"], "Food"),
    "Muffler": (["Scarf", "Shawl", "Wrap"], "Clothing"),
    "Music class": (["Art", "Gym", "Math"], "School"),
    "Newspaper": (["Magazine", "Journal", "Paper"], "Media"),
    "Newsstand": (["Kiosk", "Booth", "Stall"], "City"),
    "Nightstand": (["Dresser", "Bureau", "Chest"], "Furniture"),
    "Notebook": (["Journal", "Diary", "Pad"], "School"),
    "Notebook paper": (["Graph", "Lined", "Blank"], "School"),
    "Oboe": (["Clarinet", "Flute", "Sax"], "Music"),
    "Ocean Floor": (["Sea-bed", "Sand", "Reef"], "Nature"),
    "Odometer": (["Speedometer", "Gauge", "Dial"], "Car"),
    "Orange juice": (["Apple", "Grape", "Cranberry"], "Drink"),
    "Orchestra": (["Band", "Choir", "Group"], "Music"),
    "Overhead bin": (["Under-seat", "Closet", "Rack"], "Travel"),
    "Overpass": (["Underpass", "Bridge", "Tunnel"], "City"),
    "Oxygen mask": (["Gas-mask", "Face-mask", "Shield"], "Safety"),
    "Pancake syrup": (["Honey", "Jam", "Butter"], "Food"),
    "Pancakes": (["Waffles", "Toast", "Eggs"], "Food"),
    "Paper stack": (["Pile", "Heap", "Mound"], "Office"),
    "Paperclip": (["Staple", "Pin", "Tack"], "Office"),
    "Parking brake": (["Gas", "Clutch", "Gear"], "Car"),
    "Parking lot": (["Garage", "Space", "Spot"], "City"),
    "Passenger train": (["Freight", "Cargo", "Coal"], "Transport"),
    "Passport": (["Visa", "ID", "Card"], "Travel"),
    "Peanut butter": (["Jelly", "Honey", "Nutella"], "Food"),
    "Pencil case": (["Box", "Bag", "Pouch"], "School"),
    "Pencil sharpener": (["Knife", "Blade", "Cutter"], "School"),
    "Petting zoo": (["Farm", "Barn", "Stable"], "Fun"),
    "Pilot": (["Driver", "Captain", "Chief"], "Jobs"),
    "Playbill": (["Program", "Guide", "Menu"], "Theater"),
    "Playground": (["Park", "Field", "Yard"], "Fun"),
    "jungle gym": (["Slide", "Swing", "Sand"], "Fun"),
    "Playground kickball": (["Soccer", "Baseball", "Tag"], "Games"),
    "Playground slide": (["Swing", "Seesaw", "Bars"], "Fun"),
    "Playground swing": (["Slide", "Bars", "Sand"], "Fun"),
    "Polar bear": (["Penguin", "Seal", "Walrus"], "Animals"),
    "Policeman": (["Fireman", "Doctor", "Nurse"], "Jobs"),
    "Pony ride": (["Horse", "Camel", "Elephant"], "Fun"),
    "Popcorn": (["Chips", "Pretzels", "Nuts"], "Snack"),
    "Popsicle": (["Cone", "Cup", "Bar"], "Food"),
    "Potato chips": (["Corn", "Tortilla", "Pita"], "Snack"),
    "Principal": (["Teacher", "Coach", "Nurse"], "School"),
    "Prize counter": (["Ticket", "Token", "Coin"], "Fun"),
    "Program guide": (["Menu", "List", "Chart"], "Media"),
    "Protein bar": (["Shake", "Powder", "Drink"], "Food"),
    "Protein shake": (["Smoothie", "Juice", "Milk"], "Drink"),
    "Pumpkin pie": (["Apple", "Pecan", "Cherry"], "Food"),
    "Puppet show": (["Play", "Movie", "Act"], "Fun"),
    "Quiz paper": (["Test", "Exam", "Study"], "School"),
    "Radio": (["TV", "Phone", "Web"], "Media"),
    "Railroad": (["Track", "Line", "Path"], "Transport"),
    "Railroad bridge": (["Tunnel", "Crossing", "Switch"], "Transport"),
    "Railroad crossing": (["Signal", "Gate", "Light"], "Transport"),
    "Rainbow": (["Cloud", "Rain", "Sun"], "Weather"),
    "Raindrop": (["Snowflake", "Hail", "Sleet"], "Weather"),
    "Rainstorm": (["Snowstorm", "Wind", "Hail"], "Weather"),
    "Ramen bowl": (["Soup", "Noodle", "Broth"], "Food"),
    "Reading glasses": (["Sun-glasses", "Goggles", "Monocle"], "Items"),
    "Rearview mirror": (["Side-mirror", "Windshield", "Window"], "Car"),
    "Recess": (["Break", "Lunch", "Play"], "School"),
    "Red Rover": (["Tag", "Hide", "Seek"], "Games"),
    "Refrigerator": (["Freezer", "Cooler", "Box"], "Kitchen"),
    "Rest stop": (["Exit", "Area", "Park"], "Travel"),
    "Ringmaster": (["Clown", "Acrobat", "Tamer"], "Fun"),
    "Road trip": (["Flight", "Cruise", "Train"], "Travel"),
    "Roller coaster": (["Ride", "Track", "Car"], "Fun"),
    "Roller rink": (["Ice-rink", "Park", "Hall"], "Fun"),
    "Roller skates": (["Blades", "Shoes", "Boots"], "Fun"),
    "Rollercoaster": (["Ferris-wheel", "Carousel", "Ride"], "Fun"),
    "Root beer": (["Cola", "Soda", "Pop"], "Drink"),
    "Ruler": (["Tape", "Stick", "Yard"], "School"),
    "Runway": (["Taxiway", "Apron", "Gate"], "Travel"),
    "Runway lights": (["Beacons", "Lamps", "Spots"], "Travel"),
    "Sandbox": (["Pit", "Box", "Pile"], "Fun"),
    "Sandwich": (["Burger", "Sub", "Wrap"], "Food"),
    "Sandwich bag": (["Box", "Wrap", "Foil"], "Kitchen"),
    "School bell": (["Alarm", "Ring", "Buzz"], "School"),
    "School bus": (["Van", "Car", "Taxi"], "School"),
    "School bus stop": (["Corner", "Shelter", "Sign"], "School"),
    "School desk": (["Chair", "Table", "Bench"], "School"),
    "Science lab": (["Room", "Class", "Hall"], "School"),
    "Scissors": (["Shears", "Cutter", "Knife"], "Tools"),
    "Seat belt": (["Strap", "Buckle", "Lock"], "Safety"),
    "Break time": (["Work", "Class", "Job"], "Work"),
    "Seatbelt sign": (["Light", "Signal", "Bell"], "Travel"),
    "Security check": (["Gate", "Line", "Scan"], "Travel"),
    "See-saw": (["Swing", "Slide", "Bars"], "Fun"),
    "Shoestring": (["Lace", "Tie", "Knot"], "Clothing"),
    "Sidewalk": (["Road", "Path", "Walk"], "City"),
    "Skateboard": (["Bike", "Scooter", "Skates"], "Fun"),
    "Sleeper car": (["Coach", "Seat", "Bed"], "Transport"),
    "Slide": (["Swing", "Climb", "Jump"], "Fun"),
    "Soulmate": (["Partner", "Friend", "Love"], "Life"),
    "Smartwatch": (["Phone", "Tablet", "Band"], "Tech"),
    "Smoothie": (["Shake", "Juice", "Blend"], "Drink"),
    "Snack pack": (["Box", "Bag", "Cup"], "Food"),
    "Snack time": (["Lunch", "Dinner", "Meal"], "Food"),
    "Snowball": (["Ice", "Flake", "Drift"], "Winter"),
    "Snowfall": (["Rain", "Hail", "Sleet"], "Winter"),
    "Snowflake": (["Crystal", "Ice", "Drop"], "Winter"),
    "Snowman": (["Frosty", "Ice", "Cold"], "Winter"),
    "Snowstorm": (["Blizzard", "Squall", "Gale"], "Winter"),
    "Soda pop": (["Coke", "Pepsi", "Sprite"], "Drink"),
    "Spaghetti": (["Pasta", "Noodle", "Mac"], "Food"),
    "Spare tire": (["Wheel", "Rim", "Jack"], "Car"),
    "Sparkling water": (["Still", "Flat", "Tap"], "Drink"),
    "Speedometer": (["Tach", "Gauge", "Dial"], "Car"),
    "Spiral notebook": (["Pad", "Book", "Binder"], "School"),
    "Sports drink": (["Water", "Soda", "Juice"], "Drink"),
    "Sports jersey": (["Shirt", "Top", "Vest"], "Clothing"),
    "Spotlight": (["Flood", "Beam", "Ray"], "Theater"),
    "Stage lights": (["Spots", "Floods", "Beams"], "Theater"),
    "Stapler": (["Tape", "Glue", "Clip"], "Office"),
    "Starfish": (["Shell", "Crab", "Fish"], "Sea"),
    "Station clock": (["Watch", "Time", "Dial"], "Transport"),
    "Station master": (["Guard", "Chief", "Boss"], "Transport"),
    "Steam engine": (["Diesel", "Electric", "Coal"], "Transport"),
    "Steering wheel": (["Helm", "Tiller", "Stick"], "Car"),
    "Stir fry": (["Wok", "Pan", "Dish"], "Food"),
    "Stop sign": (["Yield", "Go", "Slow"], "City"),
    "Stopwatch": (["Timer", "Clock", "Watch"], "Sports"),
    "Strawberry": (["Berry", "Fruit", "Red"], "Food"),
    "Street sign": (["Post", "Pole", "Mark"], "City"),
    "Streetlight": (["Lamp", "Post", "Bulb"], "City"),
    "Strongman": (["Lifter", "Builder", "Gym"], "Circus"),
    "Study hall": (["Library", "Room", "Class"], "School"),
    "Subway": (["Metro", "Tube", "Train"], "Transport"),
    "Suitcase": (["Bag", "Case", "Trunk"], "Travel"),
    "Suitcase wheels": (["Handle", "Zip", "Lock"], "Travel"),
    "Sunglasses": (["Shades", "Specs", "Lens"], "Items"),
    "Sunlight": (["Moon", "Star", "Lamp"], "Nature"),
    "Sunrise": (["Sunset", "Dawn", "Dusk"], "Nature"),
    "Sunroof": (["Moonroof", "Top", "Window"], "Car"),
    "Sunset": (["Sunrise", "Dusk", "Dawn"], "Nature"),
    "Sushi roll": (["Sashimi", "Nigiri", "Maki"], "Food"),
    "Sweet tea": (["Unsweet", "Green", "Black"], "Drink"),
    "Swimming goggles": (["Mask", "Fins", "Snorkel"], "Sports"),
    "Swimming pool": (["Lake", "Pond", "Sea"], "Fun"),
    "Swing set": (["Slide", "Bars", "Sand"], "Fun"),
    "Sword swallower": (["Eater", "Breather", "Walker"], "Circus"),
    "T-shirt": (["Shirt", "Top", "Tee"], "Clothing"),
    "Tag game": (["Chase", "Race", "Run"], "Games"),
    "Taillights": (["Headlights", "Brakes", "Signals"], "Car"),
    "Tea kettle": (["Pot", "Jug", "Urn"], "Kitchen"),
    "Teacher’s pet": (["Favorite", "Star", "Best"], "School"),
    "Teapot": (["Cup", "Mug", "Saucer"], "Kitchen"),
    "Tennis court": (["Net", "Line", "Ball"], "Sports"),
    "Textbook": (["Reader", "Guide", "Manual"], "School"),
    "Ticket agent": (["Seller", "Broker", "Dealer"], "Travel"),
    "Ticket booth": (["Window", "Counter", "Desk"], "Travel"),
    "Ticket machine": (["Kiosk", "Vendor", "Box"], "Travel"),
    "Ticket ride": (["Pass", "Stub", "Slip"], "Fun"),
    "Ticket stub": (["Receipt", "Check", "Bill"], "Fun"),
    "Tightrope walker": (["Acrobat", "Clown", "Mime"], "Circus"),
    "Timetable": (["Schedule", "Plan", "Chart"], "Transport"),
    "Timpani": (["Drum", "Kettle", "Bass"], "Music"),
    "Tire tread": (["Grip", "Pattern", "Mark"], "Car"),
    "Toast": (["Bread", "Slice", "Crust"], "Food"),
    "Toll booth": (["Gate", "Lane", "Stop"], "Travel"),
    "Toll road": (["Freeway", "Highway", "Pike"], "Travel"),
    "Tooth fairy": (["Santa", "Bunny", "Elf"], "Myth"),
    "Toothbrush": (["Paste", "Floss", "Pick"], "Health"),
    "Toothpaste": (["Brush", "Rinse", "Wash"], "Health"),
    "Tow truck": (["Wrecker", "Hauler", "Puller"], "Car"),
    "Track switch": (["Lever", "Point", "Rail"], "Transport"),
    "Traffic jam": (["Gridlock", "Stop", "Wait"], "City"),
    "Traffic light": (["Signal", "Lamp", "Stop"], "City"),
    "Trail bar": (["Mix", "Nut", "Fruit"], "Food"),
    "Trail mix": (["Nuts", "Raisins", "Choco"], "Food"),
    "Train car": (["Coach", "Wagon", "Box"], "Transport"),
    "Train depot": (["Station", "Yard", "Stop"], "Transport"),
    "Train seat": (["Bench", "Chair", "Stool"], "Transport"),
    "Train station": (["Platform", "Track", "Rail"], "Transport"),
    "Train tracks": (["Rails", "Ties", "Bed"], "Transport"),
    "Train tunnel": (["Tube", "Hole", "Pass"], "Transport"),
    "Train whistle": (["Horn", "Bell", "Blast"], "Transport"),
    "Train yard": (["Depot", "Shop", "Shed"], "Transport"),
    "Trapeze artist": (["Flyer", "Catcher", "Swinger"], "Circus"),
    "Travel visa": (["Passport", "Permit", "Stamp"], "Travel"),
    "Tray table": (["Seat", "Back", "Pocket"], "Travel"),
    "Treehouse": (["Fort", "Club", "Hut"], "Fun"),
    "Trombone": (["Trumpet", "Tuba", "Horn"], "Music"),
    "Trumpet": (["Bugle", "Cornet", "Horn"], "Music"),
    "Trunk": (["Chest", "Box", "Case"], "Storage"),
    "Tunnel": (["Cave", "Mine", "Hole"], "Transport"),
    "Turbulence": (["Bump", "Shake", "Jolt"], "Travel"),
    "Turkey dinner": (["Ham", "Roast", "Feast"], "Food"),
    "Turn signal": (["Blinker", "Light", "Indicate"], "Car"),
    "Turnstile": (["Gate", "Door", "Bar"], "City"),
    "Umbrella": (["Rain", "Coat", "Boot"], "Weather"),
    "Vacuum": (["Cleaner", "Sweep", "Dust"], "House"),
    "Vacuum cleaner": (["Broom", "Mop", "Rag"], "House"),
    "Vending machine": (["Snack", "Soda", "Candy"], "Food"),
    "Violin": (["Fiddle", "Cello", "Bass"], "Music"),
    "Waiting": (["Line", "Queue", "Hold"], "Life"),
    "Waiting room": (["Lobby", "Hall", "Area"], "Health"),
    "Washing machine": (["Dryer", "Tub", "Basin"], "House"),
    "Watchout": (["Look", "See", "Head"], "Safety"),
    "Water bottle": (["Jug", "Flask", "Cup"], "Drink"),
    "Water jug": (["Pitcher", "Ewer", "Urn"], "Drink"),
    "Waterfall": (["Cascade", "Falls", "Drop"], "Nature"),
    "Watermelon": (["Melon", "Fruit", "Seed"], "Food"),
    "Water heater": (["Tank", "Boiler", "Pump"], "House"),
    "Water Skiing": (["Wake", "Board", "Boat"], "Sports"),
    "Water Slide": (["Pool", "Park", "Splash"], "Fun"),
    "Watercolor": (["Paint", "Brush", "Art"], "Art"),
    "Watch party": (["Group", "View", "Show"], "Fun"),
}

def enrich_file():
    input_file = 'raw_data.txt'
    output_file = 'raw_data_enriched.txt'
    
    with open(input_file, 'r') as f_in, open(output_file, 'w') as f_out:
        # Header
        header = f_in.readline().strip().split('\t')
        # Ensure we have enough columns or extend
        # Original: Word/Phrase, Fun Opposite, Good word, Good Opposite, Don't Like, Difficulty, Helpers(old)
        # New: ..., Helper 1, Helper 2, Helper 3, Category
        
        # We will rewrite the header
        new_header = ["Word/Phrase", "Fun Opposite", "Good word", "Good Opposite", "Don't Like", "Difficulty", "Helper 1", "Helper 2", "Helper 3", "Category"]
        f_out.write('\t'.join(new_header) + '\n')
        
        for line in f_in:
            parts = line.strip().split('\t')
            if not parts: continue
            
            word = parts[0].strip()
            
            # Get existing data (preserve up to Difficulty)
            # Some lines might be short
            row_data = parts[:6]
            while len(row_data) < 6:
                row_data.append("")
                
            # Get enrichment
            if word in enrichments:
                helpers, category = enrichments[word]
                h1, h2, h3 = helpers
            else:
                h1, h2, h3, category = "", "", "", "Uncategorized"
                
            # Append new columns
            row_data.extend([h1, h2, h3, category])
            
            f_out.write('\t'.join(row_data) + '\n')

if __name__ == "__main__":
    enrich_file()
